name: Ray2333_GRM
channels:
  - pytorch
  - nvidia
  - conda-forge
  - huggingface
dependencies:
  - python=3.10
  - pytorch=2.1.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - numpy=1.25.0
  - pandas=2.0.2
  - scipy=1.10.1
  - scikit-learn=1.4.1
  - matplotlib=3.7.1
  - seaborn=0.13.2
  - plotly=5.23.0
  - transformers=4.43.4
  - datasets=2.18.0
  - accelerate=0.32.1
  - tokenizers=0.19.1
  - huggingface_hub=0.24.3
  - safetensors=0.4.2
  - wandb=0.15.4
  - tensorboard
  - requests=2.31.0
  - pyyaml=6.0
  - tqdm=4.65.0
  - packaging=24.1
  - filelock=3.12.2
  - fsspec=2023.6.0
  - regex=2023.6.3
  - sentencepiece=0.1.99
  - pillow=9.5.0
  - sympy=1.12
  - cmake=3.26.4
  - psutil=5.9.5
  - pip
  - pip:
    # These packages are typically only available via pip
    - trl==0.8.5
    - peft==0.10.0
    - bitsandbytes==0.42.0
    - deepspeed==0.14.2
    - flash-attn==2.5.8
    - evaluate==0.4.1
    - einops==0.7.0
    - tyro==0.7.3
    - fastchat==0.1.0
